Coerce typechecker
Apparently you can't do `isinstance(thing, Tuple[str, str])`, so we
have to relax the check a bit, and then `cast` the type to satisfy the
typechecker.

The original error was thus:

```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    experiments  = synthesize_trials(block)
  File "/Users/drautb/Desktop/sweetpea-test/lib/python3.7/site-packages/sweetpea/__init__.py", line 697, in synthesize_trials
    (fresh, cnfs, reqs) = desugar(hl_block)
  File "/Users/drautb/Desktop/sweetpea-test/lib/python3.7/site-packages/sweetpea/__init__.py", line 638, in desugar
    elif isinstance(c.levels, Tuple[str, str]):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py", line 708, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py", line 716, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```